[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/keras-team/autokeras/blob/master/docs/templates/tutorial/image_classification.ipynb)

In [1]:
import tensorflow as tf
import autokeras as ak
tf.__version__

'2.1.0'

### Create synthetic multi-label dataset

In [2]:
from sklearn.datasets import make_multilabel_classification

X, Y = make_multilabel_classification(n_samples=100, n_features = 64,
                                      n_classes=3, n_labels=1,
                                      allow_unlabeled=False,
                                      random_state=1)
X = X.reshape((100, 8, 8))
X.shape, Y.shape

((100, 8, 8), (100, 3))

In [5]:
x_train, x_test, y_train, y_test = X[:80], X[80:], Y[:80], Y[80:]

### Run the ImageClassifier for multi-label classification

In [6]:
# Initialize the image classifier.
clf = ak.ImageClassifier(max_trials=2, multi_label=True) # It tries two different models.

# Feed the image classifier with training data 
# 20% of the data is used as validation data by default for tuning
# the process may run for a bit long time, please try to use GPU
clf.fit(x_train, y_train, epochs=3, verbose=2) # each model is trained for three epochs

Train for 2 steps, validate for 1 steps
Epoch 1/3
2/2 - 2s - loss: 0.6677 - accuracy: 0.6042 - val_loss: 0.6235 - val_accuracy: 0.6667
Epoch 2/3
2/2 - 0s - loss: 0.5891 - accuracy: 0.7500 - val_loss: 0.5834 - val_accuracy: 0.7292
Epoch 3/3
2/2 - 0s - loss: 0.5496 - accuracy: 0.7656 - val_loss: 0.5641 - val_accuracy: 0.7500


Train for 2 steps, validate for 1 steps
Epoch 1/3
2/2 - 20s - loss: 0.7369 - accuracy: 0.5521 - val_loss: 0.6805 - val_accuracy: 0.7500
Epoch 2/3
2/2 - 2s - loss: 0.4606 - accuracy: 0.7969 - val_loss: 0.6669 - val_accuracy: 0.7500
Epoch 3/3
2/2 - 2s - loss: 0.1101 - accuracy: 0.9740 - val_loss: 0.6499 - val_accuracy: 0.7500


INFO:tensorflow:Oracle triggered exit
Train for 3 steps, validate for 1 steps
Epoch 1/3
3/3 - 1s - loss: 0.6869 - accuracy: 0.5042 - val_loss: 0.6141 - val_accuracy: 0.7708
Epoch 2/3
3/3 - 0s - loss: 0.6067 - accuracy: 0.7083 - val_loss: 0.5424 - val_accuracy: 0.7500
Epoch 3/3
3/3 - 0s - loss: 0.5236 - accuracy: 0.8000 - val_loss: 0.5007 - val_accuracy: 0.7500



### Predict with the best model.


In [7]:
predicted_y = clf.predict(x_test)
print(predicted_y)

[[0.6313871  0.6064033  0.3243122 ]
 [0.6447389  0.6750703  0.23518789]
 [0.64807326 0.69789034 0.22812922]
 [0.6025666  0.5762541  0.33796027]
 [0.61273295 0.617567   0.28960937]
 [0.61840993 0.607622   0.3151432 ]
 [0.6507889  0.6699041  0.2780007 ]
 [0.64167434 0.6748406  0.2536208 ]
 [0.579873   0.57950723 0.33130985]
 [0.63365203 0.6661637  0.19023225]
 [0.6102978  0.6333043  0.25614443]
 [0.61803156 0.6151287  0.2660881 ]
 [0.5717129  0.6382853  0.30865255]
 [0.684091   0.65994287 0.231486  ]
 [0.7449181  0.68536055 0.202696  ]
 [0.6302187  0.6759772  0.28459364]
 [0.6869631  0.67549217 0.21319917]
 [0.6686416  0.6136327  0.31118578]
 [0.59091717 0.6478912  0.28700086]
 [0.6421396  0.6073876  0.28577906]]


### Evaluate the best model on the test data.

In [8]:
test_loss, test_acc = clf.evaluate(x_test, y_test, verbose=0)
print('Test accuracy: ', test_acc)

Test accuracy:  0.78333336


## Reference
[ImageClassifier](/image_classifier),
[AutoModel](/auto_model/#automodel-class),
[ImageBlock](/block/#imageblock-class),
[Normalization](/preprocessor/#normalization-class),
[ImageAugmentation](/preprocessor/#image-augmentation-class),
[ResNetBlock](/block/#resnetblock-class),
[ImageInput](/node/#imageinput-class),
[ClassificationHead](/head/#classificationhead-class).