In [1]:
import tensorflow as tf
import autokeras as ak

'2.3.1'

In [2]:
gpus = tf.config.experimental.list_physical_devices('GPU')
tf.config.experimental.set_visible_devices(gpus[0], 'GPU')

### Create synthetic multi-label dataset

In [3]:
from sklearn.datasets import make_multilabel_classification

X, Y = make_multilabel_classification(n_samples=200, n_features = 64,
                                      n_classes=3, n_labels=2,
                                      allow_unlabeled=False,
                                      random_state=1)
X = X.reshape((200, 8, 8))
X.shape, Y.shape

((200, 8, 8), (200, 3))

In [4]:
x_train, x_test, y_train, y_test = X[:160], X[160:], Y[:160], Y[160:]

### Run the ImageClassifier for multi-label classification

In [5]:
# Initialize the image classifier.
clf = ak.ImageClassifier(max_trials=10, multi_label=True, overwrite=True) # It tries two different pipelines.

# Feed the image classifier with training data 
# 20% of the data is used as validation data by default for tuning
# the process may run for a bit long time, please try to use GPU
clf.fit(x_train, y_train, epochs=3, verbose=2) # each model is trained for three epochs

Trial 10 Complete [00h 00m 03s]
val_loss: 0.5108350515365601

Best val_loss So Far: 0.47813382744789124
Total elapsed time: 00h 04m 08s
INFO:tensorflow:Oracle triggered exit
Epoch 1/3
5/5 - 0s - loss: 0.6323 - accuracy: 0.5063
Epoch 2/3
5/5 - 0s - loss: 0.5371 - accuracy: 0.4688
Epoch 3/3
5/5 - 0s - loss: 0.5151 - accuracy: 0.5000
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
INFO:tensorflow:Assets written to: ./image_classifier/best_model/assets



### Predict with the best model.


In [6]:
predicted_y = clf.predict(x_test)
print("The prediction shape is: {}".format(predicted_y.shape))
print("The predicted labels of the first five instances are:\n {}".format(predicted_y[:5, :]))

The prediction shape is: (40, 3)
The predicted labels of the first five instances are:
 [[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [7]:
predicted_y

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

### Evaluate the best model on the test data.

In [6]:
test_loss, test_acc = clf.evaluate(x_test, y_test, verbose=0)
print('Test accuracy: ', test_acc)

Test accuracy:  0.6000000238418579


## Reference
[ImageClassifier](/image_classifier),
[AutoModel](/auto_model/#automodel-class),
[ImageBlock](/block/#imageblock-class),
[Normalization](/preprocessor/#normalization-class),
[ImageAugmentation](/preprocessor/#image-augmentation-class),
[ResNetBlock](/block/#resnetblock-class),
[ImageInput](/node/#imageinput-class),
[ClassificationHead](/head/#classificationhead-class).