[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/keras-team/autokeras/blob/master/docs/templates/tutorial/image_classification.ipynb)

In [ ]:
import tensorflow as tf
import autokeras as ak
tf.__version__

### Create synthetic multi-label dataset

In [18]:
from sklearn.datasets import make_multilabel_classification

X, Y = make_multilabel_classification(n_samples=200, n_features = 64,
                                      n_classes=3, n_labels=2,
                                      allow_unlabeled=False,
                                      random_state=1)
X = X.reshape((200, 8, 8))
X.shape, Y.shape

((200, 8, 8), (200, 3))

In [19]:
x_train, x_test, y_train, y_test = X[:160], X[160:], Y[:160], Y[160:]

### Run the ImageClassifier for multi-label classification

In [20]:
# Initialize the image classifier.
clf = ak.ImageClassifier(max_trials=10, multi_label=True, overwrite=True) # It tries two different pipelines.

# Feed the image classifier with training data 
# 20% of the data is used as validation data by default for tuning
# the process may run for a bit long time, please try to use GPU
clf.fit(x_train, y_train, epochs=3, verbose=2) # each model is trained for three epochs

Trial 10 Complete [00h 00m 01s]
val_loss: 0.4859691262245178

Best val_loss So Far: 0.46421194076538086
Total elapsed time: 00h 02m 09s
INFO:tensorflow:Oracle triggered exit
Epoch 1/3
5/5 - 0s - loss: 0.6168 - accuracy: 0.5312
Epoch 2/3
5/5 - 0s - loss: 0.5321 - accuracy: 0.6250
Epoch 3/3
5/5 - 0s - loss: 0.5024 - accuracy: 0.5312
INFO:tensorflow:Assets written to: ./image_classifier/best_model/assets



### Predict with the best model.


In [11]:
predicted_y = clf.predict(x_test)
print("The prediction shape is: {}".format(predicted_y.shape))
print("The predicted labels of the first five instances are:\n {}".format(predicted_y[:5, :]))

The prediction shape is: (20, 3)
The predicted labels of the first five instances are:
 [[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


### Evaluate the best model on the test data.

In [6]:
test_loss, test_acc = clf.evaluate(x_test, y_test, verbose=0)
print('Test accuracy: ', test_acc)

Test accuracy:  0.6000000238418579


## Reference
[ImageClassifier](/image_classifier),
[AutoModel](/auto_model/#automodel-class),
[ImageBlock](/block/#imageblock-class),
[Normalization](/preprocessor/#normalization-class),
[ImageAugmentation](/preprocessor/#image-augmentation-class),
[ResNetBlock](/block/#resnetblock-class),
[ImageInput](/node/#imageinput-class),
[ClassificationHead](/head/#classificationhead-class).